# Test the TCF module interactively

In [1]:
from temporal_collaborative import TCF

temporal_collaborative_filtering = TCF("tgbl-wiki", decay=0.999, k=2, factor=0.8)

raw file found, skipping download
Dataset directory is  /Users/shahrad/projs/TGB_baseline/tgb_env/lib/python3.11/site-packages/tgb/data/tgbl_wiki
loading processed file


In [2]:
temporal_collaborative_filtering.train()

Training the temporal collaborative filtering model for O(9227^2) edges.


Training: 100%|██████████| 552/552 [00:09<00:00, 56.80it/s]


In [3]:
# output max and min of values in the bank dict
print("Max value in bank: ", max(temporal_collaborative_filtering.bank.values()))
print("Min value in bank: ", min(temporal_collaborative_filtering.bank.values()))


Max value in bank:  1015
Min value in bank:  1


In [4]:
# print the similarities 
print("sparse matrix: ", temporal_collaborative_filtering.sparse_bank)

sparse matrix:    (0, 0)	0.5756380598328571
  (1, 1)	180.31781280713636
  (2, 2)	76.29555830302708
  (3, 3)	107.35961131067621
  (4, 4)	52.69541553378776
  (4, 498)	128.5401555888521
  (4, 503)	99.76819356734126
  (4, 843)	76.96230763964203
  (4, 885)	19.24283672266823
  (5, 5)	129.57974317815402
  (5, 234)	0.7123616129911045
  (6, 6)	209.54539666460371
  (7, 0)	7.5995251608416226
  (7, 96)	17.702077605327105
  (7, 230)	3.6072390322843484
  (7, 692)	1.932143569136067
  (8, 7)	44.23677879135106
  (8, 66)	33.83468129773351
  (8, 123)	1.5281034701424618
  (8, 243)	40.03218860165629
  (8, 293)	3.4806668599049795
  (8, 377)	0.6387614899503485
  (8, 404)	7.6159022690394265
  (8, 821)	4.854509920585245
  (8, 869)	35.55214732845057
  (9, 8)	34.661852384462684
  (10, 9)	65.8363240670028
  (11, 10)	2.87819029916428
  (12, 11)	98.11683005779776
  (12, 354)	11.872197899773342
  (12, 769)	67.26158603164586
  (13, 12)	17.743525284546184
  (13, 432)	27.71495305538243
  (13, 457)	16.82142079479425
  (

In [5]:
# temporal_collaborative_filtering._get_most_similar_to(339189, is_source=False)

In [6]:
# a = torch.Tensor([i for i in range(10)])
# temporal_collaborative_filtering.predict(a,a,a)

# temporal_collaborative_filtering.predict(torch.Tensor([180293]), torch.Tensor([339189]), torch.Tensor([12300]))

# Validation using the test function

In [7]:
# temporal_collaborative_filtering._get_most_similar_to(343942)

In [8]:
# [(k,v) for (src, k), v in temporal_collaborative_filtering.bank.items() if src == 343942]

In [9]:
# [(k,v) for (src, k), v in temporal_collaborative_filtering.bank.items() if src == 8521]

In [10]:
temporal_collaborative_filtering.val_test(split_mode="val")

Validating the temporal collaborative filtering model.


200it [00:02, 75.83it/s]| 0/119 [00:00<?, ?it/s]
200it [00:02, 82.50it/s]| 1/119 [00:02<05:12,  2.65s/it]
200it [00:02, 81.17it/s]| 2/119 [00:05<04:55,  2.53s/it]
200it [00:02, 78.96it/s]| 3/119 [00:07<04:50,  2.51s/it]
200it [00:02, 78.41it/s]| 4/119 [00:10<04:50,  2.52s/it]
200it [00:02, 74.37it/s]| 5/119 [00:12<04:49,  2.54s/it]
200it [00:02, 77.42it/s]| 6/119 [00:15<04:53,  2.60s/it]
200it [00:02, 77.02it/s]| 7/119 [00:17<04:50,  2.60s/it]
200it [00:02, 79.00it/s]| 8/119 [00:20<04:48,  2.60s/it]
200it [00:02, 82.22it/s]| 9/119 [00:23<04:44,  2.58s/it]
200it [00:02, 75.00it/s]| 10/119 [00:25<04:37,  2.54s/it]
200it [00:02, 78.64it/s]| 11/119 [00:28<04:39,  2.59s/it]
185it [00:02, 76.15it/s]| 12/119 [00:30<04:35,  2.58s/it]
Testing:  10%|█         | 12/119 [00:33<04:56,  2.77s/it]


KeyboardInterrupt: 

# Sparse matrices

In [ ]:
import scipy as sp
import numpy as np

sparse_matrix = sp.sparse.lil_matrix((2, 2))
sparse_matrix[(0, 0)] = 2
sparse_matrix[(1, 1)] = 3
# sparse_matrix.toarray()
sim = (sparse_matrix[0].toarray()[0]).argsort()[-2:][::-1]
links = sparse_matrix[sim, 1].toarray()
count = np.count_nonzero(links)
count

1

In [ ]:
# create a sparse_matrix of size 1000*1000 and fill it with random values
import random
from time import time

sparse_matrix = sp.sparse.lil_matrix((1000, 1000))
for i in range(1000):
    for j in range(1000):
        sparse_matrix[(i, j)] = random.random()

start = time()
tmp = sparse_matrix.tocsr()
a = (tmp * 0.95).tolil()
print(time() - start)
a.toarray()

0.054186105728149414


array([[0.72274974, 0.05974487, 0.3936025 , ..., 0.94941923, 0.70311663,
        0.23243515],
       [0.21435212, 0.65513421, 0.79543666, ..., 0.27194467, 0.64011902,
        0.49849287],
       [0.40461281, 0.37380282, 0.70055513, ..., 0.85321453, 0.15787423,
        0.55341458],
       ...,
       [0.57791375, 0.13274652, 0.15706536, ..., 0.14675971, 0.02005445,
        0.00996435],
       [0.91644587, 0.10880558, 0.6839462 , ..., 0.3461443 , 0.06416255,
        0.56662281],
       [0.64365726, 0.53353195, 0.20311117, ..., 0.68947969, 0.30863722,
        0.5047343 ]])

In [ ]:
import random
from time import time

sparse_matrix = sp.sparse.lil_matrix((1000, 1000))
for i in range(1000):
    for j in range(1000):
        sparse_matrix[(i, j)] = random.random()

start = time()
tmp = sparse_matrix * 0.95
print(time() - start)

0.07507205009460449


In [ ]:
import numpy as np
a = np.array([1,2,3,0,4])
b = np.nonzero(a)[0]
b

array([0, 1, 2, 4])

In [ ]:
a = sp.sparse.lil_matrix((2, 2))
a[(0, 0)] = 1
a[(1, 1)] = 2
a[(0, 1)] = 3
a[(1, 0)] = 4
a.toarray()

array([[1., 3.],
       [4., 2.]])

In [ ]:
a.tocsr().toarray()

array([[1., 3.],
       [4., 2.]])

In [ ]:
a.tocsr().transpose().toarray() 

array([[1., 4.],
       [3., 2.]])

In [ ]:
b = a.tocsr() @ a.tocsr().transpose()

In [ ]:
b.toarray()

array([[10., 10.],
       [10., 20.]])